export const GET_ITEMS_REQUESTED = 'GET_ITEMS_REQUESTED';
export const GET_ITEMS_SUCCESS = 'GET_ITEMS_SUCCESS';
export const GET_ITEMS_FAILED = 'GET_ITEMS_FAILED';

export const POST_ITEMS_REQUESTED = 'POST_ITEMS_REQUESTED';
export const POST_ITEMS_SUCCESS = 'POST_ITEMS_SUCCESS';
export const POST_ITEMS_FAILED = 'POST_ITEMS_FAILED';